/**
 * All static roadmap card and step data for the main learning roadmaps.
 */
export const roadmaps = [
  {
    id: "arrays-mastery",
    title: "Arrays Mastery",
    description: "Master array operations, two pointers, and sliding window techniques",
    duration: "3 Days",
    difficulty: "Beginner",
    xpReward: 300,
    color: "from-blue-500 to-blue-600",
    icon: "📊",
    completed: 2,
    total: 5,
  },
  {
    id: "tree-fundamentals",
    title: "Tree Fundamentals",
    description: "Learn binary trees, BST, and tree traversal algorithms",
    duration: "5 Days",
    difficulty: "Intermediate",
    xpReward: 500,
    color: "from-green-500 to-green-600",
    icon: "🌳",
    completed: 0,
    total: 7,
  },
  {
    id: "graph-algorithms",
    title: "Graph Algorithms",
    description: "Master BFS, DFS, shortest paths, and minimum spanning trees",
    duration: "7 Days",
    difficulty: "Advanced",
    xpReward: 700,
    color: "from-purple-500 to-purple-600",
    icon: "🕸️",
    completed: 0,
    total: 10,
  },
  {
    id: "dp-patterns",
    title: "Dynamic Programming Patterns",
    description: "Learn common DP patterns and solve complex optimization problems",
    duration: "10 Days",
    difficulty: "Advanced",
    xpReward: 1000,
    color: "from-red-500 to-red-600",
    icon: "💎",
    completed: 0,
    total: 12,
  },
  {
    id: "sorting-searching",
    title: "Sorting & Searching",
    description: "Master sorting algorithms and searching techniques",
    duration: "4 Days",
    difficulty: "Beginner",
    xpReward: 350,
    color: "from-cyan-500 to-blue-600",
    icon: "🔢",
    completed: 1,
    total: 6,
  },
  {
    id: "hashing-basics",
    title: "Hash Tables & Maps",
    description: "Understand hashing, hash maps, and typical DSA problems",
    duration: "3 Days",
    difficulty: "Intermediate",
    xpReward: 400,
    color: "from-yellow-500 to-yellow-600",
    icon: "🗃️",
    completed: 0,
    total: 5,
  },
  {
    id: "graphs-and-trees",
    title: "Graphs and Trees",
    description: "Deep dive into graphs, trees, traversals, pathfinding",
    duration: "6 Days",
    difficulty: "Intermediate",
    xpReward: 600,
    color: "from-pink-500 to-purple-800",
    icon: "🌲",
    completed: 0,
    total: 8,
  },
];

export const roadmapDetails: Record<string, any> = {
  "arrays-mastery": {
    title: "Arrays Mastery",
    description: "Master array operations, two pointers, and sliding window techniques",
    duration: "3 Days",
    xpReward: 300,
    steps: [
      { id: 1, title: "Array Basics & Operations", completed: true, type: "concept" },
      { id: 2, title: "Two Pointer Technique", completed: true, type: "pattern" },
      { id: 3, title: "Sliding Window Pattern", completed: false, type: "pattern" },
      { id: 4, title: "Prefix Sum & Difference Array", completed: false, type: "technique" },
      { id: 5, title: "Subarray Problems & Kadane's", completed: false, type: "algorithm" },
    ]
  },
  "tree-fundamentals": {
    title: "Tree Fundamentals",
    description: "Learn binary trees, BST, and tree traversal algorithms",
    duration: "5 Days",
    xpReward: 500,
    steps: [
      { id: 1, title: "Binary Tree Representation", completed: false, type: "concept" },
      { id: 2, title: "Inorder, Preorder, Postorder Traversals", completed: false, type: "algorithm" },
      { id: 3, title: "Level Order Traversal (BFS)", completed: false, type: "algorithm" },
      { id: 4, title: "Binary Search Tree (BST) Operations", completed: false, type: "concept" },
      { id: 5, title: "Lowest Common Ancestor (LCA)", completed: false, type: "problem" },
      { id: 6, title: "Tree Construction & Views", completed: false, type: "problem" },
      { id: 7, title: "Balanced BST (AVL Intro)", completed: false, type: "advanced" },
    ]
  },
};
